//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFToJPGExpert {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDFToJPGExpert.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Other&gt;.
        /// </summary>
        internal static string _Other_ {
            get {
                return ResourceManager.GetString("<Other>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Page Range&gt;.
        /// </summary>
        internal static string _Page_Range_ {
            get {
                return ResourceManager.GetString("<Page Range>", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Press the OK button to download the new version.
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version has been released. Would you like to download it now ?.
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        internal static string All_Pages {
            get {
                return ResourceManager.GetString("All Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured !.
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download new version ?.
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Could not send Questionnaire !.
        /// </summary>
        internal static string Error__Could_not_send_Questionnaire__ {
            get {
                return ResourceManager.GetString("Error. Could not send Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. File or Directory not found !.
        /// </summary>
        internal static string Error__File_or_Directory_not_found__ {
            get {
                return ResourceManager.GetString("Error. File or Directory not found !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Wrong User Password for File.
        /// </summary>
        internal static string Error__Wrong_User_Password_for_File {
            get {
                return ResourceManager.GetString("Error. Wrong User Password for File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not create Directory.
        /// </summary>
        internal static string Error_could_not_create_Directory {
            get {
                return ResourceManager.GetString("Error could not create Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error could not read file !.
        /// </summary>
        internal static string Error_could_not_read_file__ {
            get {
                return ResourceManager.GetString("Error could not read file !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.Please specify a valid Height !.
        /// </summary>
        internal static string Error_Please_specify_a_valid_Height__ {
            get {
                return ResourceManager.GetString("Error.Please specify a valid Height !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.Please specify a valid Width !.
        /// </summary>
        internal static string Error_Please_specify_a_valid_Width__ {
            get {
                return ResourceManager.GetString("Error.Please specify a valid Width !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while converting file.
        /// </summary>
        internal static string Error_while_converting_file {
            get {
                return ResourceManager.GetString("Error while converting file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing List !.
        /// </summary>
        internal static string Error_while_processing_List__ {
            get {
                return ResourceManager.GetString("Error while processing List !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error wrong file type !.
        /// </summary>
        internal static string Error_wrong_file_type__ {
            get {
                return ResourceManager.GetString("Error wrong file type !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free application to convert PDF documents to images !.
        /// </summary>
        internal static string Free_application_to_convert_PDF_documents_to_images__ {
            get {
                return ResourceManager.GetString("Free application to convert PDF documents to images !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled !.
        /// </summary>
        internal static string Operation_Cancelled__ {
            get {
                return ResourceManager.GetString("Operation Cancelled !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully !.
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed with Errors !.
        /// </summary>
        internal static string Operation_completed_with_Errors__ {
            get {
                return ResourceManager.GetString("Operation completed with Errors !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Document does not exist !.
        /// </summary>
        internal static string PDF_Document_does_not_exist__ {
            get {
                return ResourceManager.GetString("PDF Document does not exist !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct User Password !.
        /// </summary>
        internal static string Please_enter_the_correct_User_Password__ {
            get {
                return ResourceManager.GetString("Please enter the correct User Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the Questionnaire !.
        /// </summary>
        internal static string Please_fill_out_the_Questionnaire__ {
            get {
                return ResourceManager.GetString("Please fill out the Questionnaire !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert a valid Password !.
        /// </summary>
        internal static string Please_insert_a_valid_Password__ {
            get {
                return ResourceManager.GetString("Please insert a valid Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a PDF Document first !.
        /// </summary>
        internal static string Please_select_a_PDF_Document_first__ {
            get {
                return ResourceManager.GetString("Please select a PDF Document first !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Output Folder !.
        /// </summary>
        internal static string Please_specify_a_valid_Output_Folder__ {
            get {
                return ResourceManager.GetString("Please specify a valid Output Folder !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid Page Range for PDF Document.
        /// </summary>
        internal static string Please_specify_a_valid_Page_Range_for_PDF_Document {
            get {
                return ResourceManager.GetString("Please specify a valid Page Range for PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Document Folder.
        /// </summary>
        internal static string Same_as_Document_Folder {
            get {
                return ResourceManager.GetString("Same as Document Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Folder of PDF Document.
        /// </summary>
        internal static string Same_Folder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Same Folder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder.
        /// </summary>
        internal static string Subfolder {
            get {
                return ResourceManager.GetString("Subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subfolder of PDF Document.
        /// </summary>
        internal static string Subfolder_of_PDF_Document {
            get {
                return ResourceManager.GetString("Subfolder of PDF Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the latest version !.
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified Error.
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add also Subdirectories ?.
        /// </summary>
        internal static string Would_you_like_to_add_also_Subdirectories__ {
            get {
                return ResourceManager.GetString("Would you like to add also Subdirectories ?", resourceCulture);
            }
        }
    }
}
